sudo: required

language: c

services:
  - docker

before_install:
  - docker pull consul
  - docker run -d -p 8500:8500 consul

  - sudo pip install hererocks
  - hererocks lua --lua 5.1 -r latest
  - source lua/bin/activate
  - luarocks install luacheck

  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install openresty cpanminus

  - sudo cpanm -q -n Test::Nginx

install:
  - sudo opm install pintsized/lua-resty-http
  - sudo opm install hamishforbes/lua-resty-consul
  - sudo opm install thibaultcha/lua-resty-mlcache


script:
- make check
- make test
